name: ivlivs_pdf_viewer
description:
  A basic cross-platform PDF viewer.
  Uses an iframe element on web and the pdfrx package on all native platforms.
version: 0.1.0
homepage: https://github.com/IVLIVS-III/ivlivs_pdf_viewer

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  pdfrx: ^1.0.83
  web: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
