name: ivlivs_pdf_viewer
description: A basic cross-platform PDF viewer.
version: 0.0.2
homepage: https://github.com/IVLIVS-III/ivlivs_pdf_viewer

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  pdfrx: ^1.0.50
  web: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
